In [1]:
import pandas as pd
import numpy as np

# ASSESSMENT 1
# MERGING AND DATA TRANSFORMATION


# Create dataframe1 with minimum 10 records
dataframe1 = pd.DataFrame({
    "ProductID": [101,102,103,104,105,106,107,108,109,110],
    "NameofProd": [
        "Laptop", "Mouse", "Keyboard", "Monitor", "Printer",
        "Speaker", "Webcam", "Router", "HardDisk", "Pendrive"
    ],
    "Price": [
        55000, 800, 1500, 12000, 9000,
        2500, 1800, 3000, 4500, 700
    ]
})


# Create dataframe2 with minimum 10 records
dataframe2 = pd.DataFrame({
    "ProductID": [101,102,103,104,105,106,107,108,109,110],
    "Company_Location": [
        "Chennai", "Vellore", "Bangalore", "Mumbai", "Delhi",
        "Hyderabad", "Pune", "Kolkata", "Coimbatore", "Madurai"
    ]
})


# Create dataframe3 with minimum 10 records
dataframe3 = pd.DataFrame({
    "ProductID": [111,112,113,114,115,116,117,118,119,120],
    "NameofProd": [
        "Tablet", "Smartphone", "Charger", "PowerBank", "Headphone",
        "Microphone", "SSD", "Smartwatch", "Camera", "Projector"
    ],
    "Price": [
        25000, 35000, 1200, 2000, 2200,
        3500, 6000, 5000, 45000, 30000
    ]
})


# Display the dataframes
print("DATAFRAME 1")
display(dataframe1)

print("DATAFRAME 2")
display(dataframe2)

print("DATAFRAME 3")
display(dataframe3)

# 1. Append dataframe1 and dataframe3


appended_dataframe = pd.concat(
    [dataframe1, dataframe3],
    ignore_index=True
)

print("APPENDED DATAFRAME")
display(appended_dataframe)

# 2. Concatenate Dataframes


# Vertical concatenation
vertical_concat = pd.concat(
    [dataframe1, dataframe3],
    axis=0,
    ignore_index=True
)

print("VERTICAL CONCATENATION")
display(vertical_concat)


# Horizontal concatenation
horizontal_concat = pd.concat(
    [
        dataframe1.reset_index(drop=True),
        dataframe2["Company_Location"].reset_index(drop=True)
    ],
    axis=1
)

print("HORIZONTAL CONCATENATION")
display(horizontal_concat)


# 3. Merge dataframe1 and dataframe2 using ProductID


merged_dataframe = pd.merge(
    dataframe1,
    dataframe2,
    on="ProductID"
)

print("MERGED DATAFRAME")
display(merged_dataframe)


# 4A. Inner Join


inner_join = pd.merge(
    dataframe1,
    dataframe2,
    on="ProductID",
    how="inner"
)

print("INNER JOIN")
display(inner_join)

# 4B. Left Join


left_join = pd.merge(
    dataframe1,
    dataframe2,
    on="ProductID",
    how="left"
)

print("LEFT JOIN")
display(left_join)

# 4C. Right Join

right_join = pd.merge(
    dataframe1,
    dataframe2,
    on="ProductID",
    how="right"
)

print("RIGHT JOIN")
display(right_join)

# 4D. Full Outer Join

full_outer_join = pd.merge(
    dataframe1,
    dataframe2,
    on="ProductID",
    how="outer"
)

print("FULL OUTER JOIN")
display(full_outer_join)

# PART B - DATA TRANSFORMATION

Akshaya = np.array([
    30, 45, 78, 25, 90,
    56, 67, 34, 82, 100
], dtype=float)

print("Original Vector:")
print(Akshaya)

# 1A. Normalize to [-3, +3]

min_value = np.min(Akshaya)
max_value = np.max(Akshaya)

norm_minus3_plus3 = (
    -3 +
    ((Akshaya - min_value) * 6) /
    (max_value - min_value)
)

print("\nNormalization [-3, +3]")
print(norm_minus3_plus3)


# 1B. Normalize to [-1, +1]


norm_minus1_plus1 = (
    -1 +
    ((Akshaya - min_value) * 2) /
    (max_value - min_value)
)

print("\nNormalization [-1, +1]")
print(norm_minus1_plus1)

# 1C. Min-Max Normalization [0,1]


minmax = (
    (Akshaya - min_value) /
    (max_value - min_value)
)

print("\nMin-Max Normalization [0,1]")
print(minmax)

# 2. Z-Score Transformation


mean_value = np.mean(Akshaya)

std_value = np.std(
    Akshaya,
    ddof=1
)

z_score = (
    Akshaya - mean_value
) / std_value

print("\nMean:")
print(mean_value)

print("\nStandard Deviation:")
print(std_value)

print("\nZ-Score Transformation:")
print(z_score)



# 3. Decimal Scaling Normalization


max_abs_value = np.max(
    np.abs(Akshaya)
)

j = int(
    np.ceil(
        np.log10(max_abs_value + 1)
    )
)

decimal_scaled = Akshaya / (10 ** j)

print("\nDecimal Scaling Value j:")
print(j)

print("\nDecimal Scaling Normalization:")
print(decimal_scaled)

DATAFRAME 1

   ProductID NameofProd  Price
0        101     Laptop  55000
1        102      Mouse    800
2        103   Keyboard   1500
3        104    Monitor  12000
4        105    Printer   9000
5        106    Speaker   2500
6        107     Webcam   1800
7        108     Router   3000
8        109   HardDisk   4500
9        110   Pendrive    700

DATAFRAME 2

   ProductID Company_Location
0        101          Chennai
1        102          Vellore
2        103        Bangalore
3        104           Mumbai
4        105            Delhi
5        106        Hyderabad
6        107             Pune
7        108          Kolkata
8        109       Coimbatore
9        110          Madurai

DATAFRAME 3

   ProductID  NameofProd  Price
0        111      Tablet  25000
1        112  Smartphone  35000
2        113     Charger   1200
3        114   PowerBank   2000
4        115   Headphone   2200
5        116  Microphone   3500
6        117         SSD   6000
7        118  Smartwatch   5000
8        119      Camera  45000
9        120   Projector  30000

APPENDED DATAFRAME

    ProductID  NameofProd  Price
0         101      Laptop  55000
1         102       Mouse    800
2         103    Keyboard   1500
3         104     Monitor  12000
4         105     Printer   9000
5         106     Speaker   2500
6         107      Webcam   1800
7         108      Router   3000
8         109    HardDisk   4500
9         110    Pendrive    700
10        111      Tablet  25000
11        112  Smartphone  35000
12        113     Charger   1200
13        114   PowerBank   2000
14        115   Headphone   2200
15        116  Microphone   3500
16        117         SSD   6000
17        118  Smartwatch   5000
18        119      Camera  45000
19        120   Projector  30000

VERTICAL CONCATENATION

    ProductID  NameofProd  Price
0         101      Laptop  55000
1         102       Mouse    800
2         103    Keyboard   1500
3         104     Monitor  12000
4         105     Printer   9000
5         106     Speaker   2500
6         107      Webcam   1800
7         108      Router   3000
8         109    HardDisk   4500
9         110    Pendrive    700
10        111      Tablet  25000
11        112  Smartphone  35000
12        113     Charger   1200
13        114   PowerBank   2000
14        115   Headphone   2200
15        116  Microphone   3500
16        117         SSD   6000
17        118  Smartwatch   5000
18        119      Camera  45000
19        120   Projector  30000

HORIZONTAL CONCATENATION

   ProductID NameofProd  Price Company_Location
0        101     Laptop  55000          Chennai
1        102      Mouse    800          Vellore
2        103   Keyboard   1500        Bangalore
3        104    Monitor  12000           Mumbai
4        105    Printer   9000            Delhi
5        106    Speaker   2500        Hyderabad
6        107     Webcam   1800             Pune
7        108     Router   3000          Kolkata
8        109   HardDisk   4500       Coimbatore
9        110   Pendrive    700          Madurai

MERGED DATAFRAME

   ProductID NameofProd  Price Company_Location
0        101     Laptop  55000          Chennai
1        102      Mouse    800          Vellore
2        103   Keyboard   1500        Bangalore
3        104    Monitor  12000           Mumbai
4        105    Printer   9000            Delhi
5        106    Speaker   2500        Hyderabad
6        107     Webcam   1800             Pune
7        108     Router   3000          Kolkata
8        109   HardDisk   4500       Coimbatore
9        110   Pendrive    700          Madurai

INNER JOIN

   ProductID NameofProd  Price Company_Location
0        101     Laptop  55000          Chennai
1        102      Mouse    800          Vellore
2        103   Keyboard   1500        Bangalore
3        104    Monitor  12000           Mumbai
4        105    Printer   9000            Delhi
5        106    Speaker   2500        Hyderabad
6        107     Webcam   1800             Pune
7        108     Router   3000          Kolkata
8        109   HardDisk   4500       Coimbatore
9        110   Pendrive    700          Madurai

LEFT JOIN

   ProductID NameofProd  Price Company_Location
0        101     Laptop  55000          Chennai
1        102      Mouse    800          Vellore
2        103   Keyboard   1500        Bangalore
3        104    Monitor  12000           Mumbai
4        105    Printer   9000            Delhi
5        106    Speaker   2500        Hyderabad
6        107     Webcam   1800             Pune
7        108     Router   3000          Kolkata
8        109   HardDisk   4500       Coimbatore
9        110   Pendrive    700          Madurai

RIGHT JOIN

   ProductID NameofProd  Price Company_Location
0        101     Laptop  55000          Chennai
1        102      Mouse    800          Vellore
2        103   Keyboard   1500        Bangalore
3        104    Monitor  12000           Mumbai
4        105    Printer   9000            Delhi
5        106    Speaker   2500        Hyderabad
6        107     Webcam   1800             Pune
7        108     Router   3000          Kolkata
8        109   HardDisk   4500       Coimbatore
9        110   Pendrive    700          Madurai

FULL OUTER JOIN

   ProductID NameofProd  Price Company_Location
0        101     Laptop  55000          Chennai
1        102      Mouse    800          Vellore
2        103   Keyboard   1500        Bangalore
3        104    Monitor  12000           Mumbai
4        105    Printer   9000            Delhi
5        106    Speaker   2500        Hyderabad
6        107     Webcam   1800             Pune
7        108     Router   3000          Kolkata
8        109   HardDisk   4500       Coimbatore
9        110   Pendrive    700          Madurai

Original Vector:
[ 30.  45.  78.  25.  90.  56.  67.  34.  82. 100.]

Normalization [-3, +3]
[-2.6  -1.4   1.24 -3.    2.2  -0.52  0.36 -2.28  1.56  3.  ]

Normalization [-1, +1]
[-0.86666667 -0.46666667  0.41333333 -1.          0.73333333 -0.17333333
  0.12       -0.76        0.52        1.        ]

Min-Max Normalization [0,1]
[0.06666667 0.26666667 0.70666667 0.         0.86666667 0.41333333
 0.56       0.12       0.76       1.        ]

Mean:
60.7

Standard Deviation:
26.65437216584843

Z-Score Transformation:
[-1.15178102 -0.58902156  0.64904924 -1.33936751  1.09925681 -0.1763313
  0.23635897 -1.00171183  0.79911843  1.47442978]

Decimal Scaling Value j:
3

Decimal Scaling Normalization:
[0.03  0.045 0.078 0.025 0.09  0.056 0.067 0.034 0.082 0.1  ]