In [1]:
import pandas as pd
import numpy as np

# ASSESSMENT 2
# DATA IMPORT, TRANSFORM AND BASIC STATISTICAL ANALYSIS

# 1. Import Dataset
url = "https://raw.githubusercontent.com/salemprakash/EDA/main/Data/Gunnels.csv"
df = pd.read_csv(url)

print("Dataset Imported Successfully")

# 2. Display First 10 Records
display(df.head(10))

# 3. Display Last 10 Records
display(df.tail(10))

# 4. Total Number of Rows and Columns
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

# 5. Display Names of All Variables
print("Column Names:")
print(df.columns.tolist())

# 6. Display Data Type of Each Variable
print("Data Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()

# 7. Display Summary Statistics
display(df.describe(include="all"))

# 8. Number of Missing Values in Each Column
print("Missing Values in Each Column:")
print(df.isnull().sum())

# 9. Total Missing Values in Dataset
total_missing = df.isnull().sum().sum()

print("Total Missing Values:")
print(total_missing)

# 10. Missing Values Column-wise
missing_columnwise = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df)) * 100
})

display(missing_columnwise)

# 11. Rows Having At Least One Missing Value
missing_rows = df[df.isnull().any(axis=1)]

print("Rows Containing Missing Values:")
display(missing_rows.head(10))

# 12. Remove Rows Having Missing Values
cleaned_dataset = df.dropna()

print("Dataset After Removing Missing Values:")
display(cleaned_dataset.head(10))

df_processed = df.copy()

numeric_columns = df_processed.select_dtypes(
    include=np.number
).columns.tolist()

categorical_columns = df_processed.select_dtypes(
    exclude=np.number
).columns.tolist()

print("Numerical Columns:")
print(numeric_columns)

print("\nCategorical Columns:")
print(categorical_columns)

# 13. Replace Missing Numerical Values Using Mean
if len(numeric_columns) >= 1:

    mean_column = numeric_columns[0]

    mean_value = df_processed[mean_column].mean()

    df_processed[mean_column] = (
        df_processed[mean_column]
        .fillna(mean_value)
    )

    print("Mean Imputation Applied On:", mean_column)

# 14. Replace Missing Values Using Median
if len(numeric_columns) >= 2:

    median_column = numeric_columns[1]

    median_value = df_processed[median_column].median()

    df_processed[median_column] = (
        df_processed[median_column]
        .fillna(median_value)
    )

    print("Median Imputation Applied On:", median_column)

# 15. Replace Categorical Missing Values Using Mode
if len(categorical_columns) >= 1:

    categorical_column = categorical_columns[0]

    mode_value = df_processed[
        categorical_column
    ].mode()[0]

    df_processed[categorical_column] = (
        df_processed[categorical_column]
        .fillna(mode_value)
    )

    print(
        "Mode Imputation Applied On:",
        categorical_column
    )

# 16. Forward Filling
df_forward = df.copy()
df_forward = df_forward.ffill()

print("Forward Filled Dataset:")
display(df_forward.head(10))

# 17. Backward Filling
df_backward = df.copy()
df_backward = df_backward.bfill()

print("Backward Filled Dataset:")
display(df_backward.head(10))

# 18. Replace Remaining Missing Values With Constant
for column in df_processed.columns:

    if pd.api.types.is_numeric_dtype(
        df_processed[column]
    ):

        df_processed[column] = (
            df_processed[column]
            .fillna(0)
        )

    else:

        df_processed[column] = (
            df_processed[column]
            .fillna("Unknown")
        )

print("Remaining Missing Values:")
print(df_processed.isnull().sum())

# 19. Remove Duplicate Records
print("Number of Duplicate Rows:")
print(df_processed.duplicated().sum())

df_processed = df_processed.drop_duplicates()

print("Duplicate Records Removed")

# 20. Convert Appropriate Variables into Categories
for column in categorical_columns:

    if column in df_processed.columns:

        df_processed[column] = (
            df_processed[column]
            .astype("category")
        )

print(df_processed.dtypes)

# 21. Rename One Column
old_column = df_processed.columns[0]

new_column = old_column + "_New"

df_processed.rename(
    columns={
        old_column: new_column
    },
    inplace=True
)

print("Renamed:")
print(old_column, "->", new_column)

print(df_processed.columns.tolist())

# 22. Create New Derived Column
numeric_columns_new = (
    df_processed
    .select_dtypes(include=np.number)
    .columns
)

if len(numeric_columns_new) >= 2:

    df_processed["Derived_Column"] = (
        df_processed[numeric_columns_new[0]]
        +
        df_processed[numeric_columns_new[1]]
    )

print("Dataset with Derived Column:")
display(df_processed.head(10))

# 23. Summary Statistics
display(
    df_processed.describe(
        include="all"
    )
)

numeric_columns_new = (
    df_processed
    .select_dtypes(include=np.number)
    .columns
)

selected_column = numeric_columns_new[0]

print(
    "Selected Numerical Column:",
    selected_column
)

# 24. Minimum and Maximum Values
minimum = df_processed[
    selected_column
].min()

maximum = df_processed[
    selected_column
].max()

print("Minimum:", minimum)
print("Maximum:", maximum)

# 25. Range
data_range = maximum - minimum

print("Range:", data_range)

# 26. Variance
variance = df_processed[
    selected_column
].var()

print("Variance:", variance)

# 27. Standard Deviation
standard_deviation = df_processed[
    selected_column
].std()

print(
    "Standard Deviation:",
    standard_deviation
)

# 28. Interquartile Range
Q1 = df_processed[
    selected_column
].quantile(0.25)

Q3 = df_processed[
    selected_column
].quantile(0.75)

IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Dataset Imported Successfully

,rownames,Gunnel,Time,Fromlow,Slope,Rw,Amphiso,Subst,Pool,Water,Cobble
0,1,0,786,190,10,0.1,0,3,0,0,0
1,2,0,794,182,10,0.0,0,3,0,0,0
2,3,0,798,178,20,0.0,0,1,0,0,0
3,4,0,800,176,70,0.3,0,1,0,1,0
4,5,0,804,172,40,0.3,0,1,0,1,0
5,6,0,808,168,60,0.3,0,1,0,1,0
6,7,0,814,162,40,0.3,0,1,0,1,0
7,8,0,817,159,0,0.9,1,1,1,1,0
8,9,0,821,155,50,0.5,0,1,0,1,0
9,10,0,826,150,20,0.1,0,1,0,0,0

,rownames,Gunnel,Time,Fromlow,Slope,Rw,Amphiso,Subst,Pool,Water,Cobble
1582,1583,1,763,115,10,1.0,3,8,0,1,1
1583,1584,0,768,120,0,1.0,1,1,1,1,0
1584,1585,0,770,122,0,1.0,2,1,0,1,0
1585,1586,0,775,127,0,1.0,0,1,0,1,0
1586,1587,0,778,130,0,1.0,0,1,0,1,0
1587,1588,0,782,134,10,1.0,0,1,0,0,0
1588,1589,0,784,136,10,1.0,0,1,1,1,0
1589,1590,0,790,142,10,1.0,0,1,0,1,0
1590,1591,0,793,145,0,1.0,1,7,0,1,1
1591,1592,0,796,148,20,1.0,0,1,1,1,0

Number of Rows: 1592
Number of Columns: 11
Column Names:
['rownames', 'Gunnel', 'Time', 'Fromlow', 'Slope', 'Rw', 'Amphiso', 'Subst', 'Pool', 'Water', 'Cobble']
Data Types:
rownames      int64
Gunnel        int64
Time          int64
Fromlow       int64
Slope         int64
Rw          float64
Amphiso       int64
Subst         int64
Pool          int64
Water         int64
Cobble        int64
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 1592 entries, 0 to 1591
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  1592 non-null   int64
 1   Gunnel    1592 non-null   int64
 2   Time      1592 non-null   int64
 3   Fromlow   1592 non-null   int64
 4   Slope     1592 non-null   int64
 5   Rw        1592 non-null   float64
 6   Amphiso   1592 non-null   int64
 7   Subst     1592 non-null   int64
 8   Pool      1592 non-null   int64
 9   Water     1592 non-null   int64
 10  Cobble    1592 non-null   int64
dtypes: float64(1), int64(10)
memory usage: 136.9 KB

,rownames,Gunnel,Time,Fromlow,Slope,Rw,Amphiso,Subst,Pool,Water,Cobble
count,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000
mean,796.500000,0.030151,705.243719,149.408920,9.503769,0.527073,0.464196,3.105528,0.202261,0.508794,0.190955
std,459.715129,0.171056,135.853638,82.662326,15.889862,0.421278,0.899039,2.787720,0.401812,0.500080,0.393177
min,1.000000,0.000000,340.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,398.750000,0.000000,623.000000,71.750000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
50%,796.500000,0.000000,712.500000,158.000000,0.000000,0.600000,0.000000,2.000000,0.000000,1.000000,0.000000
75%,1194.250000,0.000000,810.000000,224.250000,10.000000,1.000000,1.000000,4.000000,0.000000,1.000000,0.000000
max,1592.000000,1.000000,983.000000,304.000000,90.000000,1.000000,4.000000,13.000000,1.000000,1.000000,1.000000

Missing Values in Each Column:
rownames    0
Gunnel      0
Time        0
Fromlow     0
Slope       0
Rw          0
Amphiso     0
Subst       0
Pool        0
Water       0
Cobble      0
dtype: int64
Total Missing Values:
0

          Missing_Count  Missing_Percentage
rownames              0                 0.0
Gunnel                0                 0.0
Time                  0                 0.0
Fromlow               0                 0.0
Slope                 0                 0.0
Rw                    0                 0.0
Amphiso               0                 0.0
Subst                 0                 0.0
Pool                  0                 0.0
Water                 0                 0.0
Cobble                0                 0.0

Rows Containing Missing Values:

Empty DataFrame
Columns: [rownames, Gunnel, Time, Fromlow, Slope, Rw, Amphiso, Subst, Pool, Water, Cobble]
Index: []

Dataset After Removing Missing Values:

,rownames,Gunnel,Time,Fromlow,Slope,Rw,Amphiso,Subst,Pool,Water,Cobble
0,1,0,786,190,10,0.1,0,3,0,0,0
1,2,0,794,182,10,0.0,0,3,0,0,0
2,3,0,798,178,20,0.0,0,1,0,0,0
3,4,0,800,176,70,0.3,0,1,0,1,0
4,5,0,804,172,40,0.3,0,1,0,1,0
5,6,0,808,168,60,0.3,0,1,0,1,0
6,7,0,814,162,40,0.3,0,1,0,1,0
7,8,0,817,159,0,0.9,1,1,1,1,0
8,9,0,821,155,50,0.5,0,1,0,1,0
9,10,0,826,150,20,0.1,0,1,0,0,0

Numerical Columns:
['rownames', 'Gunnel', 'Time', 'Fromlow', 'Slope', 'Rw', 'Amphiso', 'Subst', 'Pool', 'Water', 'Cobble']

Categorical Columns:
[]
Mean Imputation Applied On: rownames
Median Imputation Applied On: Gunnel
Forward Filled Dataset:

,rownames,Gunnel,Time,Fromlow,Slope,Rw,Amphiso,Subst,Pool,Water,Cobble
0,1,0,786,190,10,0.1,0,3,0,0,0
1,2,0,794,182,10,0.0,0,3,0,0,0
2,3,0,798,178,20,0.0,0,1,0,0,0
3,4,0,800,176,70,0.3,0,1,0,1,0
4,5,0,804,172,40,0.3,0,1,0,1,0
5,6,0,808,168,60,0.3,0,1,0,1,0
6,7,0,814,162,40,0.3,0,1,0,1,0
7,8,0,817,159,0,0.9,1,1,1,1,0
8,9,0,821,155,50,0.5,0,1,0,1,0
9,10,0,826,150,20,0.1,0,1,0,0,0

Backward Filled Dataset:

,rownames,Gunnel,Time,Fromlow,Slope,Rw,Amphiso,Subst,Pool,Water,Cobble
0,1,0,786,190,10,0.1,0,3,0,0,0
1,2,0,794,182,10,0.0,0,3,0,0,0
2,3,0,798,178,20,0.0,0,1,0,0,0
3,4,0,800,176,70,0.3,0,1,0,1,0
4,5,0,804,172,40,0.3,0,1,0,1,0
5,6,0,808,168,60,0.3,0,1,0,1,0
6,7,0,814,162,40,0.3,0,1,0,1,0
7,8,0,817,159,0,0.9,1,1,1,1,0
8,9,0,821,155,50,0.5,0,1,0,1,0
9,10,0,826,150,20,0.1,0,1,0,0,0

Remaining Missing Values:
rownames    0
Gunnel      0
Time        0
Fromlow     0
Slope       0
Rw          0
Amphiso     0
Subst       0
Pool        0
Water       0
Cobble      0
dtype: int64
Number of Duplicate Rows:
0
Duplicate Records Removed
rownames      int64
Gunnel        int64
Time          int64
Fromlow       int64
Slope         int64
Rw          float64
Amphiso       int64
Subst         int64
Pool          int64
Water         int64
Cobble        int64
dtype: object
Renamed:
rownames -> rownames_New
['rownames_New', 'Gunnel', 'Time', 'Fromlow', 'Slope', 'Rw', 'Amphiso', 'Subst', 'Pool', 'Water', 'Cobble']
Dataset with Derived Column:

,rownames_New,Gunnel,Time,Fromlow,Slope,Rw,Amphiso,Subst,Pool,Water,Cobble,Derived_Column
0,1,0,786,190,10,0.1,0,3,0,0,0,1
1,2,0,794,182,10,0.0,0,3,0,0,0,2
2,3,0,798,178,20,0.0,0,1,0,0,0,3
3,4,0,800,176,70,0.3,0,1,0,1,0,4
4,5,0,804,172,40,0.3,0,1,0,1,0,5
5,6,0,808,168,60,0.3,0,1,0,1,0,6
6,7,0,814,162,40,0.3,0,1,0,1,0,7
7,8,0,817,159,0,0.9,1,1,1,1,0,8
8,9,0,821,155,50,0.5,0,1,0,1,0,9
9,10,0,826,150,20,0.1,0,1,0,0,0,10

,rownames_New,Gunnel,Time,Fromlow,Slope,Rw,Amphiso,Subst,Pool,Water,Cobble,Derived_Column
count,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000,1592.000000
mean,796.500000,0.030151,705.243719,149.408920,9.503769,0.527073,0.464196,3.105528,0.202261,0.508794,0.190955,796.530151
std,459.715129,0.171056,135.853638,82.662326,15.889862,0.421278,0.899039,2.787720,0.401812,0.500080,0.393177,459.723594
min,1.000000,0.000000,340.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,398.750000,0.000000,623.000000,71.750000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,398.750000
50%,796.500000,0.000000,712.500000,158.000000,0.000000,0.600000,0.000000,2.000000,0.000000,1.000000,0.000000,796.500000
75%,1194.250000,0.000000,810.000000,224.250000,10.000000,1.000000,1.000000,4.000000,0.000000,1.000000,0.000000,1194.250000
max,1592.000000,1.000000,983.000000,304.000000,90.000000,1.000000,4.000000,13.000000,1.000000,1.000000,1.000000,1592.000000

Selected Numerical Column: rownames_New
Minimum: 1
Maximum: 1592
Range: 1591
Variance: 211338.0
Standard Deviation: 459.71512918328017
Q1: 398.75
Q3: 1194.25
IQR: 795.5